"""Initial schema"""

revision = '7136b49f9643'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('who', sa.String(), nullable=True),
    sa.Column('what', sa.String(), nullable=True),
    sa.Column('payload_json', sa.String(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('params_json', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_strategies_id'), 'strategies', ['id'], unique=False)
    op.create_index(op.f('ix_strategies_name'), 'strategies', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('daily_pnl',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('realized', sa.Numeric(), nullable=True),
    sa.Column('unrealized', sa.Numeric(), nullable=True),
    sa.Column('max_dd', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'date')
    )
    op.create_index('idx_daily_pnl_user_date', 'daily_pnl', ['user_id', 'date'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('qty', sa.Numeric(), nullable=True),
    sa.Column('avg_price', sa.Numeric(), nullable=True),
    sa.Column('sl', sa.Numeric(), nullable=True),
    sa.Column('tp', sa.Numeric(), nullable=True),
    sa.Column('state', sa.Enum('open', 'closed', name='positionstate'), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_position_user_symbol', 'positions', ['user_id', 'symbol'], unique=False)
    op.create_index(op.f('ix_positions_id'), 'positions', ['id'], unique=False)
    op.create_table('risk_settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('capital', sa.Numeric(), nullable=True),
    sa.Column('risk_per_trade_pct', sa.Numeric(), nullable=True),
    sa.Column('max_daily_loss_pct', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('side', sa.String(), nullable=True),
    sa.Column('entry', sa.Numeric(), nullable=True),
    sa.Column('sl', sa.Numeric(), nullable=True),
    sa.Column('tp', sa.Numeric(), nullable=True),
    sa.Column('qty', sa.Numeric(), nullable=True),
    sa.Column('ttl_sec', sa.Integer(), nullable=True),
    sa.Column('ctx_json', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'expired', 'approved', 'rejected', 'executed', 'canceled', name='signalstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_signal_symbol_side', 'signals', ['symbol', 'side'], unique=False)
    op.create_index(op.f('ix_signals_id'), 'signals', ['id'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('approve', 'reject', name='approvalaction'), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_id'), 'approvals', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('side', sa.String(), nullable=True),
    sa.Column('qty', sa.Numeric(), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('status', sa.Enum('new', 'filled', 'canceled', 'replaced', name='orderstatus'), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_table('executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('fill_price', sa.Numeric(), nullable=True),
    sa.Column('qty', sa.Numeric(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executions_id'), 'executions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_executions_id'), table_name='executions')
    op.drop_table('executions')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_approvals_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_signals_id'), table_name='signals')
    op.drop_index('idx_signal_symbol_side', table_name='signals')
    op.drop_table('signals')
    op.drop_table('risk_settings')
    op.drop_index(op.f('ix_positions_id'), table_name='positions')
    op.drop_index('idx_position_user_symbol', table_name='positions')
    op.drop_table('positions')
    op.drop_index('idx_daily_pnl_user_date', table_name='daily_pnl')
    op.drop_table('daily_pnl')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_strategies_name'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_id'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
